### ISSUE TITLE
Where to edit the entities?

### ISSUE THREAD

**Issue by Extati** [heinoskov/huawei-solar-battery-optimizations#29]
Hi Heino

Really appriciate the efford you and the others put into this project.
I have been looking for an optimizion like this for my Huawei solar power system.

So far I'm using another addon to manage it, but this project looks like its way more optimized than the others.

The only issuse I have is that I simply cant figure out where to edit the enitites? Your readme looks like its written before the splitup in the .Yaml files? Or is it just me?
I belive I have to edit them in the huawei_solar_battery_optimization_input.yaml but not sure where.

Hope that you can help me clear out where to eidit - Really lokking forward to try this implamentation.

**Comment by heinoskov** [comment]
In the readme file see the lovelace card section... dont edit the yaml files...

Set up the Lovelace and use that to setup the entities. Maybe I need to clarify that a bit better in the readme.

**Comment by heinoskov** [comment]
Btw, this project is still work in progress with limited time for me the next few weeks...
