### ISSUE TITLE
Investigate to support Open-Meteo Solar Forecast instead of HA Solcast PV Solar Forecast Integration

### ISSUE THREAD

**Issue by heinoskov** [heinoskov/huawei-solar-battery-optimizations#4]
The current implementation of the Home Assistant Solcast PV Solar Forecast Integration is not providing sufficiently accurate predictions for solar energy production. 

This inaccuracy hampers the effectiveness of the Huawei Solar Battery Optimization system, potentially leading to suboptimal charging and discharging strategies. 

There is a need to investigate and potentially transition to the Open-Meteo Solar Forecast as an alternative solution. This change aims to improve forecast accuracy, enhance the performance of the battery optimization algorithms, and ultimately increase the overall efficiency of the solar energy system. 

The investigation should compare the accuracy, reliability, and integration capabilities of Open-Meteo with the current Solcast integration to determine if a switch would provide significant benefits to the system's performance.

**Comment by woopstar** [comment]
I checked upon this a bit last night, and the issue with Open Meteo is that it seems not to provide and hourly forecast from what I can see, as Solcast does.

it only provides entities that contains a estimated number for the next day.

**Comment by heinoskov** [comment]
Open Meteo's naming scheme is pretty crap too... not sure why it adds _4 after some of the sensors and doesnt indicate in the sensor name thats its open meteo....  

Anyways these two sensors has attributes and its like efter 15 minutes. 

sensor.energy_production_today_4
sensor.energy_production_tomorrow_4

**Comment by heinoskov** [comment]
will continue with solcast
